<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925113354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, fonction VARCHAR(100) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, email VARCHAR(150) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE beneficiaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(200) NOT NULL, type_beneficiaire VARCHAR(80) DEFAULT NULL, localite VARCHAR(150) DEFAULT NULL, contact VARCHAR(120) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE depense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, categorie VARCHAR(120) NOT NULL, montant NUMERIC(14, 2) NOT NULL, date_depense DATE DEFAULT NULL, observations TEXT DEFAULT NULL, id_pepiniere INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34059757C3E6BDF7 ON depense (id_pepiniere)');
        $this->addSql('CREATE TABLE distribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_distribution DATE NOT NULL, localite VARCHAR(150) DEFAULT NULL, quantite INT NOT NULL, projet VARCHAR(200) DEFAULT NULL, signature VARCHAR(200) DEFAULT NULL, id_lot INT DEFAULT NULL, id_espece INT NOT NULL, id_beneficiaire INT NOT NULL, id_agent INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A44837819525C141 ON distribution (id_lot)');
        $this->addSql('CREATE INDEX IDX_A44837812795145C ON distribution (id_espece)');
        $this->addSql('CREATE INDEX IDX_A44837819281AD70 ON distribution (id_beneficiaire)');
        $this->addSql('CREATE INDEX IDX_A4483781C80EDDAD ON distribution (id_agent)');
        $this->addSql('CREATE TABLE espece (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_commun VARCHAR(150) NOT NULL, nom_scientifique VARCHAR(200) DEFAULT NULL, famille VARCHAR(120) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_espece_nom ON espece (nom_commun, nom_scientifique)');
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_lot VARCHAR(80) NOT NULL, date_semis DATE DEFAULT NULL, nb_graines_semees INT DEFAULT NULL, date_germination DATE DEFAULT NULL, nb_plants_leves INT DEFAULT NULL, taux_germination NUMERIC(5, 2) DEFAULT NULL, date_sortie DATE DEFAULT NULL, id_pepiniere INT NOT NULL, id_planche INT DEFAULT NULL, id_espece INT NOT NULL, id_lot_semence INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_lot ON lot (id_pepiniere, numero_lot)');
        $this->addSql('CREATE INDEX IDX_B81291BC3E6BDF7 ON lot (id_pepiniere)');
        $this->addSql('CREATE INDEX IDX_B81291B7569B6C8 ON lot (id_planche)');
        $this->addSql('CREATE INDEX IDX_B81291B2795145C ON lot (id_espece)');
        $this->addSql('CREATE INDEX IDX_B81291BF15CFFA1 ON lot (id_lot_semence)');
        $this->addSql('CREATE TABLE lot_semence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_lot VARCHAR(80) NOT NULL, provenance VARCHAR(200) DEFAULT NULL, date_reception DATE DEFAULT NULL, id_espece INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E94E32563ED6AFAC ON lot_semence (numero_lot)');
        $this->addSql('CREATE INDEX IDX_E94E32562795145C ON lot_semence (id_espece)');
        $this->addSql('CREATE TABLE operation_culturale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_operation DATE NOT NULL, arrosage BOOLEAN NOT NULL, desherbage BOOLEAN NOT NULL, fertilisation BOOLEAN NOT NULL, traitement_phyto BOOLEAN NOT NULL, repiquage BOOLEAN NOT NULL, ombrage BOOLEAN NOT NULL, observations TEXT DEFAULT NULL, id_lot INT NOT NULL, id_agent INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_659FC15C9525C141 ON operation_culturale (id_lot)');
        $this->addSql('CREATE INDEX IDX_659FC15CC80EDDAD ON operation_culturale (id_agent)');
        $this->addSql('CREATE TABLE pepiniere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_pepiniere VARCHAR(50) NOT NULL, nom_pepiniere VARCHAR(200) NOT NULL, region VARCHAR(120) DEFAULT NULL, departement VARCHAR(120) DEFAULT NULL, sous_prefecture VARCHAR(120) DEFAULT NULL, village VARCHAR(120) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, superficie_m2 NUMERIC(12, 2) DEFAULT NULL, organisme_gestionnaire VARCHAR(200) DEFAULT NULL, date_creation DATE DEFAULT NULL, capacite_production_an INT DEFAULT NULL, date_maj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id_responsable INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_43D301D0EF9679E8 ON pepiniere (code_pepiniere)');
        $this->addSql('CREATE INDEX IDX_43D301D04A40C0F0 ON pepiniere (id_responsable)');
        $this->addSql('CREATE TABLE photo_georeferencee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url_photo TEXT NOT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, date_prise TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id_planche INT DEFAULT NULL, id_lot INT DEFAULT NULL, id_agent INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_358390E7569B6C8 ON photo_georeferencee (id_planche)');
        $this->addSql('CREATE INDEX IDX_358390E9525C141 ON photo_georeferencee (id_lot)');
        $this->addSql('CREATE INDEX IDX_358390EC80EDDAD ON photo_georeferencee (id_agent)');
        $this->addSql('CREATE TABLE planche (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_planche VARCHAR(50) NOT NULL, code_qr VARCHAR(120) DEFAULT NULL, id_pepiniere INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uq_planche ON planche (id_pepiniere, numero_planche)');
        $this->addSql('CREATE INDEX IDX_ABF41FB8C3E6BDF7 ON planche (id_pepiniere)');
        $this->addSql('CREATE TABLE stock_disponible (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plants_disponibles INT NOT NULL, plants_reserves INT NOT NULL, plants_distribues INT NOT NULL, date_maj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id_lot INT DEFAULT NULL, id_espece INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8DF5286F9525C141 ON stock_disponible (id_lot)');
        $this->addSql('CREATE INDEX IDX_8DF5286F2795145C ON stock_disponible (id_espece)');
        $this->addSql('CREATE TABLE suivi_croissance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_mesure DATE NOT NULL, hauteur_moy_cm NUMERIC(6, 2) DEFAULT NULL, diametre_collet_mm NUMERIC(6, 2) DEFAULT NULL, nb_feuilles INT DEFAULT NULL, etat_sanitaire VARCHAR(20) DEFAULT NULL, observations TEXT DEFAULT NULL, id_lot INT NOT NULL, id_agent INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B96555C9525C141 ON suivi_croissance (id_lot)');
        $this->addSql('CREATE INDEX IDX_3B96555CC80EDDAD ON suivi_croissance (id_agent)');
        $this->addSql('CREATE TABLE suivi_perte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_perte DATE NOT NULL, cause VARCHAR(20) NOT NULL, nb_plants_perdus INT DEFAULT NULL, pourcentage NUMERIC(5, 2) DEFAULT NULL, observations TEXT DEFAULT NULL, id_lot INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1FAA5DB9525C141 ON suivi_perte (id_lot)');
        $this->addSql('CREATE TABLE suivi_phytosanitaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_observation DATE NOT NULL, maladie_ravageur VARCHAR(200) DEFAULT NULL, symptomes TEXT DEFAULT NULL, traitement_applique TEXT DEFAULT NULL, produit VARCHAR(200) DEFAULT NULL, resultat VARCHAR(200) DEFAULT NULL, id_lot INT NOT NULL, id_agent INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6BF04D269525C141 ON suivi_phytosanitaire (id_lot)');
        $this->addSql('CREATE INDEX IDX_6BF04D26C80EDDAD ON suivi_phytosanitaire (id_agent)');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757C3E6BDF7 FOREIGN KEY (id_pepiniere) REFERENCES pepiniere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837819525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837812795145C FOREIGN KEY (id_espece) REFERENCES espece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A44837819281AD70 FOREIGN KEY (id_beneficiaire) REFERENCES beneficiaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BC3E6BDF7 FOREIGN KEY (id_pepiniere) REFERENCES pepiniere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291B7569B6C8 FOREIGN KEY (id_planche) REFERENCES planche (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291B2795145C FOREIGN KEY (id_espece) REFERENCES espece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BF15CFFA1 FOREIGN KEY (id_lot_semence) REFERENCES lot_semence (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot_semence ADD CONSTRAINT FK_E94E32562795145C FOREIGN KEY (id_espece) REFERENCES espece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation_culturale ADD CONSTRAINT FK_659FC15C9525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation_culturale ADD CONSTRAINT FK_659FC15CC80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pepiniere ADD CONSTRAINT FK_43D301D04A40C0F0 FOREIGN KEY (id_responsable) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_georeferencee ADD CONSTRAINT FK_358390E7569B6C8 FOREIGN KEY (id_planche) REFERENCES planche (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_georeferencee ADD CONSTRAINT FK_358390E9525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_georeferencee ADD CONSTRAINT FK_358390EC80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planche ADD CONSTRAINT FK_ABF41FB8C3E6BDF7 FOREIGN KEY (id_pepiniere) REFERENCES pepiniere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_disponible ADD CONSTRAINT FK_8DF5286F9525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_disponible ADD CONSTRAINT FK_8DF5286F2795145C FOREIGN KEY (id_espece) REFERENCES espece (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_croissance ADD CONSTRAINT FK_3B96555C9525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_croissance ADD CONSTRAINT FK_3B96555CC80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_perte ADD CONSTRAINT FK_B1FAA5DB9525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_phytosanitaire ADD CONSTRAINT FK_6BF04D269525C141 FOREIGN KEY (id_lot) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_phytosanitaire ADD CONSTRAINT FK_6BF04D26C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE depense DROP CONSTRAINT FK_34059757C3E6BDF7');
        $this->addSql('ALTER TABLE distribution DROP CONSTRAINT FK_A44837819525C141');
        $this->addSql('ALTER TABLE distribution DROP CONSTRAINT FK_A44837812795145C');
        $this->addSql('ALTER TABLE distribution DROP CONSTRAINT FK_A44837819281AD70');
        $this->addSql('ALTER TABLE distribution DROP CONSTRAINT FK_A4483781C80EDDAD');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BC3E6BDF7');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291B7569B6C8');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291B2795145C');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BF15CFFA1');
        $this->addSql('ALTER TABLE lot_semence DROP CONSTRAINT FK_E94E32562795145C');
        $this->addSql('ALTER TABLE operation_culturale DROP CONSTRAINT FK_659FC15C9525C141');
        $this->addSql('ALTER TABLE operation_culturale DROP CONSTRAINT FK_659FC15CC80EDDAD');
        $this->addSql('ALTER TABLE pepiniere DROP CONSTRAINT FK_43D301D04A40C0F0');
        $this->addSql('ALTER TABLE photo_georeferencee DROP CONSTRAINT FK_358390E7569B6C8');
        $this->addSql('ALTER TABLE photo_georeferencee DROP CONSTRAINT FK_358390E9525C141');
        $this->addSql('ALTER TABLE photo_georeferencee DROP CONSTRAINT FK_358390EC80EDDAD');
        $this->addSql('ALTER TABLE planche DROP CONSTRAINT FK_ABF41FB8C3E6BDF7');
        $this->addSql('ALTER TABLE stock_disponible DROP CONSTRAINT FK_8DF5286F9525C141');
        $this->addSql('ALTER TABLE stock_disponible DROP CONSTRAINT FK_8DF5286F2795145C');
        $this->addSql('ALTER TABLE suivi_croissance DROP CONSTRAINT FK_3B96555C9525C141');
        $this->addSql('ALTER TABLE suivi_croissance DROP CONSTRAINT FK_3B96555CC80EDDAD');
        $this->addSql('ALTER TABLE suivi_perte DROP CONSTRAINT FK_B1FAA5DB9525C141');
        $this->addSql('ALTER TABLE suivi_phytosanitaire DROP CONSTRAINT FK_6BF04D269525C141');
        $this->addSql('ALTER TABLE suivi_phytosanitaire DROP CONSTRAINT FK_6BF04D26C80EDDAD');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE beneficiaire');
        $this->addSql('DROP TABLE depense');
        $this->addSql('DROP TABLE distribution');
        $this->addSql('DROP TABLE espece');
        $this->addSql('DROP TABLE lot');
        $this->addSql('DROP TABLE lot_semence');
        $this->addSql('DROP TABLE operation_culturale');
        $this->addSql('DROP TABLE pepiniere');
        $this->addSql('DROP TABLE photo_georeferencee');
        $this->addSql('DROP TABLE planche');
        $this->addSql('DROP TABLE stock_disponible');
        $this->addSql('DROP TABLE suivi_croissance');
        $this->addSql('DROP TABLE suivi_perte');
        $this->addSql('DROP TABLE suivi_phytosanitaire');
    }
}
